import { Manrope, /* Geist_Mono */ } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Family Friends",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${manrope.variable} ${geistMono.variable} antialiased`}
        className={`${manrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
