import { Manrope /* Geist_Mono */ } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const manrope = Manrope({ subsets: ["latin"], display: "swap" });

// const manrope = Manrope({
//   variable: "--font-manrope",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "DummyJSON Browser",
  // description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Kan IKKE finde ud af hvordan jeg importerer fonts på den fancy,
        optimerede next.js måde,så bruteforcer igennem vanilla HTML: */}
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${manrope.className} antialiased overflow-x-hidden`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
